use anchor_lang::prelude::*;
use arcium_anchor::prelude::*;

// Links this program to the Arcis circuit named "check_contacts"
const COMP_DEF_OFFSET_CHECK_CONTACTS: u32 = comp_def_offset("check_contacts");

// Your program address — already generated by arcium init, keep this as-is
declare_id!("BwxmXwa3Gfz7xFpF5qMvuKSQunimR5HzzMmrb7VPWh4m");

// ============================================================
// CONSTANTS
// ============================================================
pub const MAX_REGISTERED_USERS: usize = 50;
pub const MAX_CONTACTS_PER_BATCH: usize = 10;

// Seed for the registered users account (one global list for the app)
pub const REGISTERED_USERS_SEED: &[u8] = b"registered_users";

#[arcium_program]
pub mod invisi_phone {
    use super::*;
    use arcium_client::idl::arcium::types::CircuitSource;
    use arcium_client::idl::arcium::types::OffChainCircuitSource;
    // --------------------------------------------------------
    // FUNCTION 1: init_check_contacts_comp_def
    // WHEN: Called ONCE at first deploy
    // WHAT: Registers the check_contacts circuit with Arcium
    // --------------------------------------------------------
    pub fn init_check_contacts_comp_def(
    ctx: Context<InitCheckContactsCompDef>
) -> Result<()> {
    init_comp_def(
        ctx.accounts,
        Some(CircuitSource::OffChain(OffChainCircuitSource {
            source: "https://dwoonbiedwpwwmlknxvn.supabase.co/storage/v1/object/public/arcium1/check_contacts.arcis".to_string(),
            hash: [
                0xf8, 0x2f, 0x2d, 0xa4, 0x4a, 0x3b, 0x8a, 0x86,
                0xa3, 0x25, 0x5e, 0xaa, 0x01, 0x9d, 0xcf, 0x25,
                0x30, 0xdb, 0x79, 0x75, 0xa1, 0x70, 0x92, 0x09,
                0xa8, 0xdb, 0x00, 0xc9, 0xae, 0x8d, 0x94, 0x61,
            ],
        })),
        None, // finalize_authority
    )?;
    Ok(())
}
    // --------------------------------------------------------
    // FUNCTION 2: init_registered_users
    // WHEN: Called ONCE after deploy
    // WHAT: Creates the on-chain account that holds registered users
    // ANALOGY: Like CREATE TABLE registered_users in SQL
    // --------------------------------------------------------
    pub fn init_registered_users(
        ctx: Context<InitRegisteredUsers>
    ) -> Result<()> {
        let registered = &mut ctx.accounts.registered_users;
        registered.count = 0;
        registered.users = Vec::new();
        Ok(())
    }

    // --------------------------------------------------------
    // FUNCTION 3: register_user
    // WHEN: Called when a user joins InvisiPhone
    // WHAT: Adds their wallet address to the registered users list
    // ANALOGY: Like INSERT INTO registered_users (wallet) VALUES (?)
    //
    // NOTE: wallet_address is public here — this is intentional.
    // The registered set is the "server side" of the PSI.
    // The CONTACTS list (user side) is what stays private.
    // --------------------------------------------------------
    pub fn register_user(
        ctx: Context<RegisterUser>,
        wallet_address: [u8; 32],   // the user's wallet as 32 bytes
    ) -> Result<()> {
        let registered = &mut ctx.accounts.registered_users;

        // Check we haven't hit the max
        require!(
            registered.count < MAX_REGISTERED_USERS as u8,
            ErrorCode::RegistryFull
        );

        // Check they're not already registered (avoid duplicates)
        for i in 0..registered.count as usize {
            if registered.users[i] == wallet_address {
                return Err(ErrorCode::AlreadyRegistered.into());
            }
        }

        // Add them to the list
      
        registered.users.push(wallet_address);
        registered.count += 1;
        // Emit event so frontend knows registration succeeded
        emit!(UserRegisteredEvent {
            wallet: wallet_address,
            total_users: registered.count,
        });

        Ok(())
    }

    // --------------------------------------------------------
    // FUNCTION 4: check_contacts
    // WHEN: Called from frontend when user wants to find friends
    // WHAT: Accepts encrypted contact batch + encrypted registered set,
    //       queues them to Arcium MXE for private comparison
    // ANALOGY: Like POST /find-friends but with encrypted data
    //
    // Parameters:
    //   computation_offset    — unique ID for this computation
    //   contacts_ciphertext   — user's encrypted contact list ([u8; 32])
    //   registered_ciphertext — encrypted registered users set ([u8; 32])
    //   pubkey                — user's x25519 public key (gets the result)
    //   nonce                 — replay protection
    // --------------------------------------------------------
    pub fn check_contacts(
        ctx: Context<CheckContacts>,
        computation_offset: u64,
        contacts_ciphertext: [u8; 32],      // encrypted ContactBatch
        registered_ciphertext: [u8; 32],    // encrypted RegisteredSet
        pubkey: [u8; 32],                   // user's encryption public key
        nonce: u128,                        // replay protection
    ) -> Result<()> {
        ctx.accounts.sign_pda_account.bump = ctx.bumps.sign_pda_account;

        // Package the encrypted inputs for Arcium
        let args = ArgBuilder::new()
            .x25519_pubkey(pubkey)                      // result recipient
            .plaintext_u128(nonce)                      // replay protection
            .encrypted_u8(contacts_ciphertext)          // user's secret contacts
            .encrypted_u8(registered_ciphertext)        // registered users (encrypted)
            .build();

        // Send to Arcium MXE — "when done, call check_contacts_callback"
        queue_computation(
            ctx.accounts,
            computation_offset,
            args,
            vec![CheckContactsCallback::callback_ix(
                computation_offset,
                &ctx.accounts.mxe_account,
                &[],
            )?],
            1,  // one output: the matches array [u8; 10]
            0,  // standard priority
        )?;

        Ok(())
    }

    // --------------------------------------------------------
    // FUNCTION 5: check_contacts_callback
    // WHEN: Called AUTOMATICALLY by Arcium when MXE finishes
    // WHAT: Verifies result, emits event with encrypted matches
    // You never call this — Arcium does
    // --------------------------------------------------------
    #[arcium_callback(encrypted_ix = "check_contacts")]
    pub fn check_contacts_callback(
        ctx: Context<CheckContactsCallback>,
        output: SignedComputationOutputs<CheckContactsOutput>,
    ) -> Result<()> {

        // Verify the result came from Arcium (cryptographic signature check)
        let o = match output.verify_output(
            &ctx.accounts.cluster_account,
            &ctx.accounts.computation_account,
        ) {
            Ok(CheckContactsOutput { field_0 }) => field_0,
            Err(_) => return Err(ErrorCode::AbortedComputation.into()),
        };

        // Emit event — frontend is listening for this
        // matches = encrypted [1,0,1,0,0,1,0,0,0,0]
        // 1 = that contact is registered, 0 = not registered
        // Only the user can decrypt this with their private key
        emit!(ContactMatchEvent {
            matches: o.ciphertexts[0],  // encrypted match results
            nonce: o.nonce.to_le_bytes(),
        });

        Ok(())
    }
}

// ============================================================
// ON-CHAIN DATA ACCOUNT
// Stores the registered users list
// ============================================================
#[account]
pub struct RegisteredUsers {
    pub count: u8,                              // how many users registered
    pub users: Vec<[u8; 32]>, // wallet addresses
}

impl RegisteredUsers {
    // Space calculation for Anchor:
    // 8 (discriminator) + 1 (count) + (32 * 50) (users array)
    pub const SPACE: usize = 8 + 1 + 4 + (32 * MAX_REGISTERED_USERS);
// 8 discriminator + 1 count + 4 vec length + (32 * 50) data
}

// ============================================================
// ACCOUNT STRUCTS
// ============================================================

// Accounts for init_registered_users (run once after deploy)
#[derive(Accounts)]
pub struct InitRegisteredUsers<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,

    #[account(
        init,
        payer = payer,
        space = RegisteredUsers::SPACE,
        seeds = [REGISTERED_USERS_SEED],
        bump,
    )]
    pub registered_users: Account<'info, RegisteredUsers>,

    pub system_program: Program<'info, System>,
}

// Accounts for register_user
#[derive(Accounts)]
pub struct RegisterUser<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,

    #[account(
        mut,
        seeds = [REGISTERED_USERS_SEED],
        bump,
    )]
    pub registered_users: Account<'info, RegisteredUsers>,

    pub system_program: Program<'info, System>,
}

// Accounts for check_contacts (queuing the computation)
#[queue_computation_accounts("check_contacts", payer)]
#[derive(Accounts)]
#[instruction(computation_offset: u64)]
pub struct CheckContacts<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,

    #[account(
        init_if_needed,
        space = 9,
        payer = payer,
        seeds = [&SIGN_PDA_SEED],
        bump,
        address = derive_sign_pda!(),
    )]
    pub sign_pda_account: Account<'info, ArciumSignerAccount>,

    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,

    #[account(
        mut,
        address = derive_mempool_pda!(mxe_account, ErrorCode::ClusterNotSet)
    )]
    /// CHECK: mempool_account, checked by the arcium program.
    pub mempool_account: UncheckedAccount<'info>,

    #[account(
        mut,
        address = derive_execpool_pda!(mxe_account, ErrorCode::ClusterNotSet)
    )]
    /// CHECK: executing_pool, checked by the arcium program.
    pub executing_pool: UncheckedAccount<'info>,

    #[account(
        mut,
        address = derive_comp_pda!(computation_offset, mxe_account, ErrorCode::ClusterNotSet)
    )]
    /// CHECK: computation_account, checked by the arcium program.
    pub computation_account: UncheckedAccount<'info>,

    #[account(
        address = derive_comp_def_pda!(COMP_DEF_OFFSET_CHECK_CONTACTS)
    )]
    pub comp_def_account: Account<'info, ComputationDefinitionAccount>,

    #[account(
        mut,
        address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet)
    )]
    pub cluster_account: Account<'info, Cluster>,

    #[account(
        mut,
        address = ARCIUM_FEE_POOL_ACCOUNT_ADDRESS,
    )]
    pub pool_account: Account<'info, FeePool>,

    #[account(
        mut,
        address = ARCIUM_CLOCK_ACCOUNT_ADDRESS
    )]
    pub clock_account: Account<'info, ClockAccount>,

    pub system_program: Program<'info, System>,
    pub arcium_program: Program<'info, Arcium>,
}

// Accounts for check_contacts_callback (Arcium calls this)
#[callback_accounts("check_contacts")]
#[derive(Accounts)]
pub struct CheckContactsCallback<'info> {
    pub arcium_program: Program<'info, Arcium>,

    #[account(
        address = derive_comp_def_pda!(COMP_DEF_OFFSET_CHECK_CONTACTS)
    )]
    pub comp_def_account: Account<'info, ComputationDefinitionAccount>,

    #[account(address = derive_mxe_pda!())]
    pub mxe_account: Account<'info, MXEAccount>,

    /// CHECK: computation_account, checked by arcium program.
    pub computation_account: UncheckedAccount<'info>,

    #[account(
        address = derive_cluster_pda!(mxe_account, ErrorCode::ClusterNotSet)
    )]
    pub cluster_account: Account<'info, Cluster>,

    #[account(address = ::anchor_lang::solana_program::sysvar::instructions::ID)]
    /// CHECK: instructions_sysvar, checked by the account constraint
    pub instructions_sysvar: AccountInfo<'info>,
}

// Accounts for init_check_contacts_comp_def (run once at deploy)
#[init_computation_definition_accounts("check_contacts", payer)]
#[derive(Accounts)]
pub struct InitCheckContactsCompDef<'info> {
    #[account(mut)]
    pub payer: Signer<'info>,

    #[account(
        mut,
        address = derive_mxe_pda!()
    )]
    pub mxe_account: Box<Account<'info, MXEAccount>>,

    #[account(mut)]
    /// CHECK: comp_def_account, checked by arcium program.
    pub comp_def_account: UncheckedAccount<'info>,

    #[account(
        mut,
        address = derive_mxe_lut_pda!(mxe_account.lut_offset_slot)
    )]
    /// CHECK: address_lookup_table, checked by arcium program.
    pub address_lookup_table: UncheckedAccount<'info>,

    #[account(address = LUT_PROGRAM_ID)]
    /// CHECK: lut_program is the Address Lookup Table program.
    pub lut_program: UncheckedAccount<'info>,

    pub arcium_program: Program<'info, Arcium>,
    pub system_program: Program<'info, System>,
}

// ============================================================
// EVENTS
// Frontend listens for these
// ============================================================

#[event]
pub struct UserRegisteredEvent {
    pub wallet: [u8; 32],       // who just registered
    pub total_users: u8,        // total registered users now
}

#[event]
pub struct ContactMatchEvent {
    pub matches: [u8; 32],      // encrypted match results [1,0,1,0...]
    pub nonce: [u8; 16],        // needed by frontend to decrypt
}

// ============================================================
// ERRORS
// ============================================================
#[error_code]
pub enum ErrorCode {
    #[msg("Computation was aborted or tampered with")]
    AbortedComputation,
    #[msg("No Arcium cluster assigned yet")]
    ClusterNotSet,
    #[msg("Registry is full (max 50 users)")]
    RegistryFull,
    #[msg("Wallet already registered")]
    AlreadyRegistered,
}